### ISSUE TITLE
Playback broken

### ISSUE THREAD

**Issue by hallonstedt** [mtr81/plugin.video.viaplay#4]
Playback does not work for me anymore. The screen flickers and then returns to the menu. Best case I get to see like 2 seconds of the video followed by a message that "Playback failed - see logfile for details". I have attached a debug logfile. I redacted some of the very long lists of videos in response to URL requests to content.viaplay.se to make it more readable. 
to me, it's not obvious  what the problem is.

**Comment by mtr81** [comment]
Hi,
In log I see 'ParentalGuidancePinChallengeNeededError' error during playback episodes of series "Modern love". Viaplay add-on does not include the option of entering the required PIN code.

**Comment by hallonstedt** [comment]
That was indeed the problem. I could watch Paw Patrol but not The Good Doctor! 
Turns out logging out and re-activating the device solved the issue. Thanks for helping me diagnose!
